# -*- coding: utf-8 -*-
"""0080.2026atw_FAST_reduction_class.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15luAHR_Yw1Wy6Ym3kFzbRhjNjeH7TIvo
"""

# I like to keep all my installs in the first block, and my imports in the second
!pip install astropy --upgrade
!pip install photutils

# Imports for handling files
from google.colab import drive
import os
import glob
import re


# The usual suspects for math and plotting
import numpy as np
import matplotlib.pyplot as plt

# FITS handling
from astropy.io import fits

# Some future functions we'll need
from scipy.ndimage import median_filter
from scipy.signal import find_peaks

drive.mount('/content/drive', force_remount=True)

"""First let's make sure we have the relevant data. Go to the following shared Google drive:

https://drive.google.com/drive/folders/1hzmeY2HsWOXLGjOYVO9QdRZJ4krincTb?usp=sharing

Click on Example_data -> Organize -> Add Shortcut and mount this folder on "MyDrive". Then you can access via your own Google Drive account.

"""

path = 'drive/MyDrive/Astron100-data-Sp26/FAST/2026.0317/'
sn_files = glob.glob(path + '0080.2026atw.fits')

# Open the FITS file
with fits.open(sn_files[0]) as hdu_list:
    print(f"Opened FITS file: {sn_files[0]}")
    print("Number of HDUs:", len(hdu_list))
    print("\n--- HDU Information ---")
    for i, hdu in enumerate(hdu_list):
        print(f"HDU {i}: Type = {type(hdu)}, Name = {hdu.name}, Data Type = {hdu.header.get('XTENSION', 'Primary')}")

# Notice the different trims!

# Open the FITS file
with fits.open(sn_files[0]) as hdu_list:
    # Get the header from the primary HDU (HDU 0)
    primary_header = hdu_list[0].header
    for key, value in primary_header.items():
           print(key,":", value)

# Open the FITS file
with fits.open(sn_files[0]) as hdu_list:
    fig, ax = plt.subplots(1, 1, figsize=(10, 10))
    hdu = hdu_list[0]
    image_data = hdu.data

    im = ax.imshow(image_data, origin='lower', cmap='gray', vmin=np.percentile(image_data, 1), vmax=np.percentile(image_data, 99))
    ax.set_title(f"HDU {i}: {hdu.name}")
    ax.set_xlabel("X-pixels")
    ax.set_ylabel("Y-pixels")

    plt.tight_layout()
    plt.show()

# The 'path' variable is already defined from previous cells.

bias_files = glob.glob(path + '*BIAS*.fits')

bias_stack = []

print(f"Found {len(bias_files)} BIAS files for FAST in {path}")

if not bias_files:
    print("No BIAS files found. Please check the path and file names.")
else:
    # Using header-defined sections:
    # BIASSEC : [2:30,1:161] -> 0-indexed: [1:29]
    # TRIMSEC : [35:2715,1:161] -> 0-indexed: [34:2714]
    oscan_start, oscan_end = 1, 29
    trim_start, trim_end = 34, 2714
    CCD_to_reduce = 0

    for fn in bias_files:
        try:
            data = fits.getdata(fn, CCD_to_reduce)
        except IndexError:
            print(f"Warning: FITS file {os.path.basename(fn)} does not have HDU {CCD_to_reduce}. Skipping.")
            continue

        # --- Overscan subtraction (Left side) ---
        overscan = data[:, oscan_start:oscan_end]
        bias_level = np.median(overscan, axis=1)

        data_corr = data - bias_level[:, None]

        # --- Trim to 'good' part of CCD ---
        data_trim = data_corr[:, trim_start:trim_end]

        bias_stack.append(data_trim)

    if bias_stack:
        bias_stack = np.array(bias_stack)
        med_bias = np.median(bias_stack, axis=0)

        print(f"Created median bias. Shape: {med_bias.shape}")

        plt.figure(figsize=(12,6))

        # --- Median Bias Image ----
        plt.subplot(121)
        plt.imshow(med_bias,
                   vmin=np.percentile(med_bias, 5),
                   vmax=np.percentile(med_bias, 95),
                   cmap='gray', origin='lower')
        plt.title("Median Bias (Overscan Corrected & Trimmed)")

        # --- Histogram ---
        plt.subplot(122)
        plt.hist(med_bias.flatten(), bins=100)
        plt.title("Median Bias Histogram")
        plt.xlabel("ADU")
        plt.ylabel("Count")

        plt.tight_layout()
        plt.show()
    else:
        print("No valid data processed.")

all_flat_files = glob.glob(path + '*FLAT*.fits')
flat_stack = []
print("--- Found Flat Files ---")
if not all_flat_files:
    print("No FLAT files found. Please check the path and file names.")
else:
    for fn in all_flat_files:
        try:
            data = fits.getdata(fn, CCD_to_reduce)
        except IndexError:
            print(f"Warning: FITS file {os.path.basename(fn)} does not have HDU {CCD_to_reduce}. Skipping.")
            continue

        # --- Overscan subtraction (Left side) ---
        overscan = data[:, oscan_start:oscan_end]
        bias_level = np.median(overscan, axis=1)

        data_corr = data - bias_level[:, None]

        # --- Trim to 'good' part of CCD ---
        data_trim = data_corr[:, trim_start:trim_end]

        flat_stack.append(data_trim)

    if flat_stack:
        flat_stack = np.array(flat_stack)
        med_flat = np.median(flat_stack, axis=0)

        med_flat = med_flat / np.median(med_flat) # I have added this line for the flat!

        print(f"Created median flat. Shape: {med_flat.shape}")

        plt.figure(figsize=(12,6))

        # --- Median Flat Image ----
        plt.subplot(121)
        plt.imshow(med_flat,
                   vmin=np.percentile(med_flat, 5),
                   vmax=np.percentile(med_flat, 95),
                   cmap='gray', origin='lower')
        plt.title("Median Flat (Overscan Corrected & Trimmed)")

        # --- Histogram ---
        plt.subplot(122)
        plt.hist(med_flat.flatten(), bins=100)
        plt.title("Median Flat Histogram")
        plt.xlabel("ADU")
        plt.ylabel("Count")

        plt.tight_layout()
        plt.show()

flat_files = all_flat_files # Assigning all found flat files as the ones to be processed

science_file = glob.glob(path + '0080.2026atw.fits')[0]

# Load raw data
science = fits.getdata(science_file, CCD_to_reduce)

# --- Overscan subtraction (Left side) ---
overscan = science[:, oscan_start:oscan_end]
bias_level_science = np.median(overscan, axis=1)
science_corr = science - bias_level_science[:, None]

# --- Trim to 'good' part of CCD ---
science_trim = science_corr[:, trim_start:trim_end]

# --- Bias subtraction ---
science_biascorr = science_trim - med_bias

# --- Flat division ---
science_reduced = science_biascorr / med_flat

print(f"Science image reduced: {os.path.basename(science_file)}")
print(f"Final shape: {science_reduced.shape}")

plt.figure(figsize=(12, 6))
plt.imshow(science_reduced,
           vmin=np.percentile(science_reduced, 1),
           vmax=np.percentile(science_reduced, 99),
           cmap='gray', origin='lower')
plt.title(f"Reduced Science Image: {os.path.basename(science_file)}")
plt.xlabel("X-pixels")
plt.ylabel("Y-pixels")
plt.show()

"""Here, we will extract the "trace" of the spectrum. That is, we will isolate the object from the 2D spectrum."""

spatial_profile = np.nanmedian(science_reduced, axis=1)
plt.plot(spatial_profile)
plt.show()
spatial_profile = np.nanmedian(science_reduced, axis=0)
plt.plot(spatial_profile)

# --- Plotting ---
plt.figure(figsize=(15, 10))
plt.subplot(2, 1, 1)


# 1. Find the trace (spatial profile)
# We sum along the dispersion axis (columns) to find the peak in Y
spatial_profile = np.nanmedian(science_reduced, axis=1)
y_peak = np.argmax(spatial_profile)


# Subplot 1: Spatial Profile to show the trace identification
plt.plot(spatial_profile)
plt.axvline(y_peak, color='red', linestyle='--', label=f'Trace Peak (Y={y_peak})')
plt.title("Spatial Profile (Collapsed along X-axis)")
plt.xlabel("Y-pixel (Spatial)")
plt.ylabel("Median Flux")
plt.legend()

print(f"Detected peak of the trace at Y-pixel: {y_peak}")

# 2. Extract the 1D spectrum
# Define an aperture width (e.g., +/- 3 pixels around the peak)
aperture_half_width = 2
extraction_range = slice(y_peak - aperture_half_width, y_peak + aperture_half_width)
spectrum_1d = np.nansum(science_reduced[extraction_range, :], axis=0)



# Subplot 2: The extracted 1D spectrum
plt.subplot(2, 1, 2)
plt.plot(spectrum_1d, color='black')
plt.title("Extracted 1D Spectrum of NGC 4151")
plt.xlabel("X-pixel (Dispersion)")
plt.ylabel("Total Flux (ADU)")
plt.grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

# 1. Define sky regions (rows away from the target trace at Y=81)
sky_regions = np.concatenate([science_reduced[20:50, :], science_reduced[110:140, :]], axis=0)

# 2. Create the master sky spectrum
sky_spectrum_1d = np.nanmedian(sky_regions, axis=0)

# 3. Scale the sky to the aperture width
aperture_factor = 4
sky_scaled = sky_spectrum_1d * aperture_factor

# 4. Subtract sky from the target spectrum
spectrum_1d_skysub = spectrum_1d - sky_scaled

# 5. Apply a small median filter for smoothing (window of 3 pixels)
spectrum_smoothed = median_filter(spectrum_1d_skysub, size=3)

# --- Visualization ---
plt.figure(figsize=(15, 6))
plt.plot(spectrum_1d_skysub, color='gray', alpha=0.4, label='Sky-Subtracted (Raw)')
plt.plot(spectrum_smoothed, color='black', label='Sky-Subtracted (Median Smoothed)')

plt.title("Sky Subtraction & Smoothing Results")
plt.xlabel("Pixels")
plt.ylabel("Flux (ADU)")
plt.ylim([0,10000])
plt.legend()
plt.grid(True, alpha=0.3)
plt.show()

"""Now, we must convert our pixels to a wavelength. To do that, we need the arc lamp that shows atomic lines at known wavelengths. You can see an old image of the arc lamp [here](http://tdc-www.harvard.edu/instruments/fast/fast_cal.html)

I am being lazy and just using the first arc we took. In reality, you need to take the *closest* arc!!!
"""

arc_files = glob.glob(path + '*0080.COMP*.fits')
print(f"Found {len(arc_files)} arc files.")

if arc_files:
    # Pick the first arc file
    arc_file = arc_files[0]
    print(f"Processing arc: {os.path.basename(arc_file)}")

    # 1. Load data
    arc_data = fits.getdata(arc_file, CCD_to_reduce)

    # 2. Basic Reduction (No Flat Field for Arcs)
    # Overscan
    arc_overscan = arc_data[:, oscan_start:oscan_end]
    arc_bias_level = np.median(arc_overscan, axis=1)
    arc_corr = arc_data - arc_bias_level[:, None]

    # Trim and Bias Subtract using header-defined regions
    arc_trim = arc_corr[:, trim_start:trim_end]
    arc_reduced = arc_trim - med_bias

    # 3. Extract 1D Arc Spectrum using the SAME trace as the science image
    # extraction_range was defined in the science extraction cell
    arc_spectrum_1d = np.nansum(arc_reduced[extraction_range, :], axis=0)

    # Plot it
    plt.figure(figsize=(15, 5))
    plt.plot(arc_spectrum_1d, color='blue')
    plt.title(f"Extracted 1D Arc Spectrum: {os.path.basename(arc_file)}")
    plt.xlabel("X-pixel (Dispersion)")
    plt.ylabel("Flux (ADU)")
    plt.grid(True, alpha=0.3)
    plt.show()
else:
    print("No arc files found! Please check the file naming pattern.")

# 1. Automatically find peaks in the arc spectrum
# Reducing distance and height to ensure we catch the fainter edge lines
peaks, properties = find_peaks(arc_spectrum_1d, height=np.percentile(arc_spectrum_1d, 90), distance=10)

# Extract the X-pixel positions of the peaks
detected_pixels = peaks
print(f"Found {len(detected_pixels)} emission lines in the arc.")

plt.figure(figsize=(15, 5))
plt.plot(arc_spectrum_1d, color='blue', alpha=0.5)
plt.plot(detected_pixels, arc_spectrum_1d[detected_pixels], "x", color='red', label='Detected Peaks')
plt.title("Automated Peak Detection for Arc Calibration")
plt.xlabel("X-pixel")
plt.ylabel("Flux")

plt.legend()
plt.show()

from scipy.interpolate import interp1d

# 1. This is a solution from the Ar lamp
Ar_lamp = """
	         69.83 3575.40181  3577.6364   4.0 1 1 ArII
	        173.81 3724.56556  3719.2638   4.0 1 1 ArII
	        200.30 3762.70113  3767.1883   4.0 1 1 ArII
	        389.14 4036.03156  4034.9488   4.0 1 1 ArII
	        397.75 4048.55337   4045.561   4.0 1 1 ArII
	        416.37 4075.63949  4073.1541   4.0 1 1 ArI
	        438.19 4107.41827    4105.07   4.0 1 1 ArII
	        457.35 4135.33392  4132.8886   4.0 1 1 ArII
	        475.71 4162.10809   4159.762   4.0 1 1 ArII
	        497.89 4194.48163   4201.858   4.0 1 1 ArI
	        523.36 4231.67628  4238.4126   4.0 1 1 ArI
	        557.22 4281.17982  4278.7316   4.0 1 1 ArII
	        572.78 4303.95145  4301.8591   4.0 1 1 ArI
	        590.92 4330.50502   4334.779   4.0 1 1 ArII
	        642.35 4405.88237  4402.2222   4.0 1 1 ArII
	        692.30  4479.2032  4483.0679   4.0 1 1 ArI
	        710.87 4506.48197   4511.998   4.0 1 1 ArII
	        740.21 4549.61034  4546.3258   4.0 1 1 ArII
	        763.62 4584.04803  4580.6326   4.0 1 1 ArII
	        770.81 4594.62313  4591.1837   4.0 1 1 ArII
	        776.48 4602.96328  4610.8582   4.0 1 1 ArI
	        817.14 4662.82399   4659.205   4.0 1 1 ArII
	        864.14 4732.08769  4737.2302   4.0 1 1 ArII
	        889.98 4770.18611  4766.1968   4.0 1 1 ArII
	        917.99 4811.49062  4807.3635   4.0 1 1 ArI
	        946.37 4853.37534  4849.1639   4.0 1 1 ArII
	        968.19 4885.57568  4881.2263   4.0 1 1 ArII
	       1020.98 4963.51916  4966.4649   4.0 1 1 ArII
	       1056.26 5015.62824  5018.5619   4.0 1 1 ArII
	       1084.34 5057.12633  5063.4483   4.0 1 1 ArII
	       1747.80 6036.35344   6033.797   4.0 1 1 ArII
	       1842.34 6175.70772  6173.9855   4.0 1 1 ArII
	       2183.31 6678.67084   6679.126   4.0 1 1 ArII
	       2234.43 6754.18301   6754.698   4.0 1 1 ArII
	       2314.47 6872.49738   6873.185   4.0 1 1 ArII
	       2378.10  6966.6166   6967.352   4.0 1 1 ArI
	       2421.98 7031.56808    7032.19   4.0 1 1 ArII
	       2447.01 7068.64731   7069.167   4.0 1 1 ArII
	       2501.04 7148.70742   7148.012   4.0 1 1 ArII
	       2586.37 7275.29815    7274.94   4.0 1 1 ArI
	       2661.77 7387.30618   7386.014   4.0 1 1 ArI
"""

# Extract reference wavelengths from the user template
ref_lambdas = []
initial_pixels = []
initial_wavelengths = []
for line in Ar_lamp.strip().split('\n'):
    parts = line.strip().split()
    if len(parts) >= 3:
        initial_pixels.append(float(parts[0]))
        initial_wavelengths.append(float(parts[1]))
        ref_lambdas.append(float(parts[2]))

initial_pixels = np.array(initial_pixels)
initial_wavelengths = np.array(initial_wavelengths)
ref_lambdas = np.unique(ref_lambdas)
ref_lambdas_sorted = np.sort(ref_lambdas)

# Initial Model (Order 2)
initial_poly_coeffs = np.polyfit(initial_pixels, initial_wavelengths, 2)
initial_wavelength_model = np.poly1d(initial_poly_coeffs)

# Match detected peaks to the new Argon reference lines -- initial guess
detected_waves = initial_wavelength_model(detected_pixels)

matched_pixels = []
matched_wavelengths = []
tolerance = 15.0 # angstrom

for i, p in enumerate(detected_pixels):
	# First, calculate the DIFFERENCE between my detected pixel and the references -- so I can find the closest!
	differences = np.abs(ref_lambdas_sorted - detected_waves[i])
	best_match = np.argmin(differences)
	if differences[best_match] < tolerance:
		matched_pixels.append(p)
		matched_wavelengths.append(ref_lambdas_sorted[best_match])


# Refine Solution (Order 2)
coefficients_of_new_solution = np.polyfit(matched_pixels, matched_wavelengths, 2)
final_wavelength_model = np.poly1d(coefficients_of_new_solution)


# We want to return:
wavelengths = final_wavelength_model(np.arange(len(spectrum_1d)))

# Plot to see how well we're doing....
plt.plot(matched_pixels, matched_wavelengths,'o')
plt.plot(matched_pixels, final_wavelength_model(matched_pixels))
plt.xlabel('Pixel Value')
plt.ylabel('Wavelength Value')

plt.figure(figsize=(15, 6))
plt.plot(wavelengths, arc_spectrum_1d, color='blue', label='Calibrated Arc')

# Plot reference lines as vertical dashed lines
for wave in ref_lambdas:
    plt.axvline(wave, color='red', linestyle='--', alpha=0.6)
    if wave == 7514.7: # Specifically label the right-most anchor for confirmation
        plt.text(wave, np.max(arc_spectrum_1d), f'{wave}A', rotation=90, verticalalignment='top', color='red')

plt.title("Wavelength Calibration Check: Data vs. Reference Lines")
plt.xlabel("Wavelength (Angstroms)")
plt.ylabel("Flux (ADU)")
plt.legend(['Arc Spectrum', 'Reference Line Positions'])
plt.show()

import plotly.graph_objects as go
import numpy as np
import os

# ================================
# Redshift
# ================================
z = 0.056

# ================================
# Rest wavelengths of Balmer series (Å)
# ================================
balmer_rest = {
    'H-alpha': 6562.8,
    'H-beta': 4861.3,
    'H-gamma': 4340.5,
    'H-delta': 4101.7
}

# ================================
# Create interactive plot
# ================================
fig_cal = go.Figure()

# ================================
# Add UNCALIBRATED spectrum
# ================================
fig_cal.add_trace(go.Scatter(
    x=wavelengths,
    y=spectrum_smoothed,
    mode='lines',
    line=dict(color='black', width=1.5),
    name='Uncalibrated Spectrum (ADU)'
))

# ================================
# Add redshifted Balmer lines
# ================================
for name, rest_wave in balmer_rest.items():
    obs_wave = rest_wave * (1 + z)

    fig_cal.add_vline(
        x=obs_wave,
        line_dash="dash",
        line_color="red",
        annotation_text=f"{name} (z={z})",
        annotation_position="top"
    )

# ================================
# Layout
# ================================
fig_cal.update_layout(
    title=f'Uncalibrated Spectrum (0080.2026atw.fits, z={z})',
    xaxis_title='Wavelength (Ångströms)',
    yaxis_title='Flux (ADU)',
    template='plotly_white',
    hovermode='x',
    xaxis=dict(range=[wavelengths[0], wavelengths[-1]])
)

fig_cal.show()

print(f"Processing arc: {os.path.basename(arc_file)}")

# =========================================================
# SAVE UNCALI BRATED SPECTRUM
# =========================================================
uncalibrated_spectrum = np.column_stack((wavelengths, spectrum_smoothed))

output_file = "uncalibrated_2026atw.txt"

np.savetxt(
    output_file,
    uncalibrated_spectrum,
    header="Wavelength(Angstrom)   Flux(ADU)",
    fmt="%.6f"
)

print(f"Saved uncalibrated spectrum to: {output_file}")

path = 'drive/MyDrive/Astron100-data-Sp26/FAST/2026.0317/'
star_files = glob.glob(path + '0053.Hiltner600.fits')

# Open the FITS file
with fits.open(star_files[0]) as hdu_list:
    print(f"Opened FITS file: {star_files[0]}")
    print("Number of HDUs:", len(hdu_list))
    print("\n--- HDU Information ---")
    for i, hdu in enumerate(hdu_list):
        print(f"HDU {i}: Type = {type(hdu)}, Name = {hdu.name}, Data Type = {hdu.header.get('XTENSION', 'Primary')}")

# Notice the different trims!

# Open the FITS file
with fits.open(star_files[0]) as hdu_list:
    # Get the header from the primary HDU (HDU 0)
    primary_header = hdu_list[0].header
    for key, value in primary_header.items():
           print(key,":", value)

# Open the FITS file
with fits.open(star_files[0]) as hdu_list:
    fig, ax = plt.subplots(1, 1, figsize=(10, 10))
    hdu = hdu_list[0]
    image_data = hdu.data

    im = ax.imshow(image_data, origin='lower', cmap='gray', vmin=np.percentile(image_data, 1), vmax=np.percentile(image_data, 99))
    ax.set_title(f"HDU {i}: {hdu.name}")
    ax.set_xlabel("X-pixels")
    ax.set_ylabel("Y-pixels")

    plt.tight_layout()
    plt.show()

star_science_file = glob.glob(path + '0053.Hiltner600.fits')[0]

# Load raw data
star_science = fits.getdata(star_science_file, CCD_to_reduce)

# --- Overscan subtraction (Left side) ---
overscan = star_science[:, oscan_start:oscan_end]
bias_level_star_science = np.median(overscan, axis=1)
star_science_corr = star_science - bias_level_star_science[:, None]

# --- Trim to 'good' part of CCD ---
star_science_trim = star_science_corr[:, trim_start:trim_end]

# --- Bias subtraction ---
star_science_biascorr = star_science_trim - med_bias

# --- Flat division ---
star_science_reduced = star_science_biascorr / med_flat

print(f"Science image reduced: {os.path.basename(star_science_file)}")
print(f"Final shape: {star_science_reduced.shape}")

plt.figure(figsize=(12, 6))
plt.imshow(star_science_reduced,
           vmin=np.percentile(star_science_reduced, 1),
           vmax=np.percentile(star_science_reduced, 99),
           cmap='gray', origin='lower')
plt.title(f"Reduced Science Image: {os.path.basename(star_science_file)}")
plt.xlabel("X-pixels")
plt.ylabel("Y-pixels")
plt.show()

star_spatial_profile = np.nanmedian(star_science_reduced, axis=1)
plt.plot(star_spatial_profile)
plt.show()
star_spatial_profile = np.nanmedian(star_science_reduced, axis=0)
plt.plot(star_spatial_profile)

# --- Plotting ---
plt.figure(figsize=(15, 10))
plt.subplot(2, 1, 1)


# 1. Find the trace (spatial profile)
# We sum along the dispersion axis (columns) to find the peak in Y
star_spatial_profile = np.nanmedian(star_science_reduced, axis=1)
y_peak = np.argmax(star_spatial_profile)


# Subplot 1: Spatial Profile to show the trace identification
plt.plot(star_spatial_profile)
plt.axvline(y_peak, color='red', linestyle='--', label=f'Trace Peak (Y={y_peak})')
plt.title("Star Spatial Profile (Collapsed along X-axis)")
plt.xlabel("Y-pixel (Spatial)")
plt.ylabel("Median Flux")
plt.legend()

print(f"Detected peak of the trace at Y-pixel: {y_peak}")

# 2. Extract the 1D spectrum
# Define an aperture width (e.g., +/- 3 pixels around the peak)
aperture_half_width = 2
extraction_range = slice(y_peak - aperture_half_width, y_peak + aperture_half_width)
star_spectrum_1d = np.nansum(star_science_reduced[extraction_range, :], axis=0)



# Subplot 2: The extracted 1D spectrum
plt.subplot(2, 1, 2)
plt.plot(star_spectrum_1d, color='black')
plt.title("Extracted 1D Spectrum of NGC 4151")
plt.xlabel("X-pixel (Dispersion)")
plt.ylabel("Total Flux (ADU)")
plt.grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

# 1. Define sky regions (rows away from the target trace at Y=81)
star_sky_regions = np.concatenate([star_science_reduced[20:50, :], star_science_reduced[110:140, :]], axis=0)

# 2. Create the master sky spectrum
star_sky_spectrum_1d = np.nanmedian(star_sky_regions, axis=0)

# 3. Scale the sky to the aperture width
aperture_factor = 4
star_sky_scaled = star_sky_spectrum_1d * aperture_factor

# 4. Subtract sky from the target spectrum
star_spectrum_1d_skysub = star_spectrum_1d - star_sky_scaled

# 5. Apply a small median filter for smoothing (window of 3 pixels)
star_spectrum_smoothed = median_filter(star_spectrum_1d_skysub, size=6)

# --- Visualization ---
plt.figure(figsize=(15, 6))
plt.plot(star_spectrum_1d_skysub, color='gray', alpha=0.4, label='Star Sky-Subtracted (Raw)')
plt.plot(star_spectrum_smoothed, color='black', label='Sky-Subtracted (Median Smoothed)')

plt.title("Star Sky Subtraction & Smoothing Results")
plt.xlabel("Pixels")
plt.ylabel("Flux (ADU)")
plt.ylim([0,10000])
plt.legend()
plt.grid(True, alpha=0.3)
plt.show()

star_arc_files = glob.glob(path + '*0054.COMP*.fits')
print(f"Found {len(star_arc_files)} arc files.")

if star_arc_files:
    # Pick the first arc file
    star_arc_file = star_arc_files[0]
    print(f"Processing arc: {os.path.basename(star_arc_file)}")

    # 1. Load data
    star_arc_data = fits.getdata(star_arc_file, CCD_to_reduce)

    # 2. Basic Reduction (No Flat Field for Arcs)
    # Overscan
    star_arc_overscan = star_arc_data[:, oscan_start:oscan_end]
    star_arc_bias_level = np.median(star_arc_overscan, axis=1)
    star_arc_corr = star_arc_data - star_arc_bias_level[:, None]

    # Trim and Bias Subtract using header-defined regions
    star_arc_trim = star_arc_corr[:, trim_start:trim_end]
    star_arc_reduced = star_arc_trim - med_bias

    # 3. Extract 1D Arc Spectrum using the SAME trace as the science image
    # extraction_range was defined in the science extraction cell
    star_arc_spectrum_1d = np.nansum(star_arc_reduced[extraction_range, :], axis=0)

    # Plot it
    plt.figure(figsize=(15, 5))
    plt.plot(star_arc_spectrum_1d, color='blue')
    plt.title(f"Extracted 1D Arc Spectrum: {os.path.basename(star_arc_file)}")
    plt.xlabel("X-pixel (Dispersion)")
    plt.ylabel("Flux (ADU)")
    plt.grid(True, alpha=0.3)
    plt.show()
else:
    print("No arc files found! Please check the file naming pattern.")

# 1. Automatically find peaks in the arc spectrum
# Reducing distance and height to ensure we catch the fainter edge lines
peaks, properties = find_peaks(star_arc_spectrum_1d, height=np.percentile(star_arc_spectrum_1d, 90), distance=10)

# Extract the X-pixel positions of the peaks
star_detected_pixels = peaks
print(f"Found {len(star_detected_pixels)} emission lines in the arc.")

plt.figure(figsize=(15, 5))
plt.plot(star_arc_spectrum_1d, color='blue', alpha=0.5)
plt.plot(star_detected_pixels, star_arc_spectrum_1d[star_detected_pixels], "x", color='red', label='Detected Peaks')
plt.title("Automated Peak Detection for Arc Calibration")
plt.xlabel("X-pixel")
plt.ylabel("Flux")

plt.legend()
plt.show()

from scipy.interpolate import interp1d

# 1. This is a solution from the Ar lamp
Ar_lamp = """
	         69.83 3575.40181  3577.6364   4.0 1 1 ArII
	        173.81 3724.56556  3719.2638   4.0 1 1 ArII
	        200.30 3762.70113  3767.1883   4.0 1 1 ArII
	        389.14 4036.03156  4034.9488   4.0 1 1 ArII
	        397.75 4048.55337   4045.561   4.0 1 1 ArII
	        416.37 4075.63949  4073.1541   4.0 1 1 ArI
	        438.19 4107.41827    4105.07   4.0 1 1 ArII
	        457.35 4135.33392  4132.8886   4.0 1 1 ArII
	        475.71 4162.10809   4159.762   4.0 1 1 ArII
	        497.89 4194.48163   4201.858   4.0 1 1 ArI
	        523.36 4231.67628  4238.4126   4.0 1 1 ArI
	        557.22 4281.17982  4278.7316   4.0 1 1 ArII
	        572.78 4303.95145  4301.8591   4.0 1 1 ArI
	        590.92 4330.50502   4334.779   4.0 1 1 ArII
	        642.35 4405.88237  4402.2222   4.0 1 1 ArII
	        692.30  4479.2032  4483.0679   4.0 1 1 ArI
	        710.87 4506.48197   4511.998   4.0 1 1 ArII
	        740.21 4549.61034  4546.3258   4.0 1 1 ArII
	        763.62 4584.04803  4580.6326   4.0 1 1 ArII
	        770.81 4594.62313  4591.1837   4.0 1 1 ArII
	        776.48 4602.96328  4610.8582   4.0 1 1 ArI
	        817.14 4662.82399   4659.205   4.0 1 1 ArII
	        864.14 4732.08769  4737.2302   4.0 1 1 ArII
	        889.98 4770.18611  4766.1968   4.0 1 1 ArII
	        917.99 4811.49062  4807.3635   4.0 1 1 ArI
	        946.37 4853.37534  4849.1639   4.0 1 1 ArII
	        968.19 4885.57568  4881.2263   4.0 1 1 ArII
	       1020.98 4963.51916  4966.4649   4.0 1 1 ArII
	       1056.26 5015.62824  5018.5619   4.0 1 1 ArII
	       1084.34 5057.12633  5063.4483   4.0 1 1 ArII
	       1747.80 6036.35344   6033.797   4.0 1 1 ArII
	       1842.34 6175.70772  6173.9855   4.0 1 1 ArII
	       2183.31 6678.67084   6679.126   4.0 1 1 ArII
	       2234.43 6754.18301   6754.698   4.0 1 1 ArII
	       2314.47 6872.49738   6873.185   4.0 1 1 ArII
	       2378.10  6966.6166   6967.352   4.0 1 1 ArI
	       2421.98 7031.56808    7032.19   4.0 1 1 ArII
	       2447.01 7068.64731   7069.167   4.0 1 1 ArII
	       2501.04 7148.70742   7148.012   4.0 1 1 ArII
	       2586.37 7275.29815    7274.94   4.0 1 1 ArI
	       2661.77 7387.30618   7386.014   4.0 1 1 ArI
"""

# Extract reference wavelengths from the user template
ref_lambdas = []
initial_pixels = []
initial_wavelengths = []
for line in Ar_lamp.strip().split('\n'):
    parts = line.strip().split()
    if len(parts) >= 3:
        initial_pixels.append(float(parts[0]))
        initial_wavelengths.append(float(parts[1]))
        ref_lambdas.append(float(parts[2]))

initial_pixels = np.array(initial_pixels)
initial_wavelengths = np.array(initial_wavelengths)
ref_lambdas = np.unique(ref_lambdas)
ref_lambdas_sorted = np.sort(ref_lambdas)

# Initial Model (Order 2)
initial_poly_coeffs = np.polyfit(initial_pixels, initial_wavelengths, 2)
initial_wavelength_model = np.poly1d(initial_poly_coeffs)

# Match detected peaks to the new Argon reference lines -- initial guess
star_detected_waves = initial_wavelength_model(star_detected_pixels)

matched_pixels = []
matched_wavelengths = []
tolerance = 15.0 # angstrom

for i, p in enumerate(star_detected_pixels):
	# First, calculate the DIFFERENCE between my detected pixel and the references -- so I can find the closest!
	differences = np.abs(ref_lambdas_sorted - star_detected_waves[i])
	best_match = np.argmin(differences)
	if differences[best_match] < tolerance:
		matched_pixels.append(p)
		matched_wavelengths.append(ref_lambdas_sorted[best_match])


# Refine Solution (Order 2)
star_coefficients_of_new_solution = np.polyfit(matched_pixels, matched_wavelengths, 2)
final_wavelength_model = np.poly1d(star_coefficients_of_new_solution)


# We want to return:
star_wavelengths = final_wavelength_model(np.arange(len(spectrum_1d)))

# Plot to see how well we're doing....
plt.plot(matched_pixels, matched_wavelengths,'o')
plt.plot(matched_pixels, final_wavelength_model(matched_pixels))
plt.xlabel('Pixel Value')
plt.ylabel('Wavelength Value')

plt.figure(figsize=(15, 6))
plt.plot(star_wavelengths, star_arc_spectrum_1d, color='blue', label='Calibrated Arc')

# Plot reference lines as vertical dashed lines
for wave in ref_lambdas:
    plt.axvline(wave, color='red', linestyle='--', alpha=0.6)
    if wave == 7514.7: # Specifically label the right-most anchor for confirmation
        plt.text(wave, np.max(arc_spectrum_1d), f'{wave}A', rotation=90, verticalalignment='top', color='red')

plt.title("Star Wavelength Calibration Check: Data vs. Reference Lines")
plt.xlabel("Wavelength (Angstroms)")
plt.ylabel("Flux (ADU)")
plt.legend(['Arc Spectrum', 'Reference Line Positions'])
plt.show()

import plotly.graph_objects as go

# Redshift provided by user
z = 0.056

# Rest wavelengths of the Balmer series (Angstroms)
balmer_rest = {
    'H-alpha': 6562.8,
    'H-beta': 4861.3,
    'H-gamma': 4340.5,
    'H-delta': 4101.7
}

# Create an interactive plot of the calibrated spectrum
fig_cal = go.Figure()

# Add the spectrum
fig_cal.add_trace(go.Scatter(
    x=star_wavelengths,
    y=star_spectrum_smoothed,
    mode='lines',
    line=dict(color='black', width=1.5),
    name='Calibrated Spectrum'
))

# Add vertical lines for redshifted Balmer series
for name, rest_wave in balmer_rest.items():
    obs_wave = rest_wave * (1 + z)

    fig_cal.add_vline(
        x=obs_wave,
        line_dash="dash",
        line_color="red",
        annotation_text=f"{name} (z={z})",
        annotation_position="top"
    )

fig_cal.update_layout(
    title=f'Interactive Wavelength Calibrated Spectrum (z={z} Balmer Overlays for Hiltner 600)',
    xaxis_title='Wavelength (Ångströms)',
    yaxis_title='Flux (ADU)',
    template='plotly_white',
    hovermode='x',
    xaxis=dict(range=[star_wavelengths[0], star_wavelengths[-1]])
)

fig_cal.show()
print(f"Processing arc: 0054.COMP.fits")

import numpy as np
import plotly.graph_objects as go
from astropy.io import fits
from scipy.ndimage import gaussian_filter1d

# =========================================================
# 1. Load standard star (reference flux)
# =========================================================
std_file = "fhilt600.dat.txt"
std_data = np.loadtxt(std_file)

std_wave = std_data[:, 0]
std_flux = std_data[:, 1]   # already physical flux

# =========================================================
# 2. Interpolate standard flux onto instrument grid
#    (safe: avoid extrapolation artifacts)
# =========================================================
interp_std_flux = np.interp(
    star_wavelengths,
    std_wave,
    std_flux,
    left=np.nan,
    right=np.nan
)

# =========================================================
# 3. Exposure time
# =========================================================
hdr = fits.getheader(star_science_file)
exptime = hdr["EXPTIME"]

# =========================================================
# 4. Convert observed star spectrum to counts/sec
# =========================================================
obs_rate = star_spectrum_smoothed / exptime

# =========================================================
# 5. Build robust mask (this is critical)
# =========================================================
finite = np.isfinite(interp_std_flux) & np.isfinite(obs_rate)

# remove low S/N regions in observed spectrum
signal_floor = np.nanmedian(obs_rate) * 0.2

mask = (
    finite &
    (obs_rate > signal_floor) &
    (obs_rate > 0)
)

# =========================================================
# 6. Raw sensitivity (unstable version first)
# =========================================================
sens_raw = np.full_like(wavelengths, np.nan, dtype=float)

sens_raw[mask] = interp_std_flux[mask] / obs_rate[mask]

# =========================================================
# 7. Stabilize sensitivity
#    - replace NaNs
#    - smooth only physically meaningful curve
# =========================================================
valid = np.isfinite(sens_raw)

sens_filled = np.interp(
    star_wavelengths,
    star_wavelengths[valid],
    sens_raw[valid]
)

# smooth gently (do NOT over-smooth)
sensitivity = gaussian_filter1d(sens_filled, sigma=3)

# enforce positivity (physical constraint)
sensitivity = np.clip(sensitivity, 0, np.nanmax(sensitivity))

# =========================================================
# 8. Sanity check: reconstruct star spectrum
# =========================================================
flux_calibrated = obs_rate * sensitivity

# =========================================================
# 9. Plot calibration check
# =========================================================
fig = go.Figure()

fig.add_trace(go.Scatter(
    x=star_wavelengths,
    y=flux_calibrated,
    mode="lines",
    name="Recovered Star Flux",
    line=dict(color="black")
))

fig.add_trace(go.Scatter(
    x=star_wavelengths,
    y=interp_std_flux,
    mode="lines",
    name="Reference Flux",
    line=dict(color="blue", dash="dot")
))

fig.update_layout(
    title="Flux-calibrated Hiltner600 Spectrum",
    xaxis_title="Wavelength (Å)",
    yaxis_title="Flux (erg s⁻¹ cm⁻² Å⁻¹)",
    template="plotly_white"
)

fig.show()

# =========================================================
# 10. Sensitivity function plot
# =========================================================
fig2 = go.Figure()

fig2.add_trace(go.Scatter(
    x=star_wavelengths,
    y=sensitivity,
    mode="lines",
    name="Sensitivity Function",
    line=dict(color="green")
))

fig2.update_layout(
    title="Instrument Response Function (Improved)",
    xaxis_title="Wavelength (Å)",
    yaxis_title="Sensitivity",
    template="plotly_white"
)

fig2.show()

# =========================================================
# 11. Save calibrated star spectrum (diagnostic only)
# =========================================================
np.savetxt(
    "calibrated_hiltner600.txt",
    np.column_stack((star_wavelengths, flux_calibrated)),
    header="Wavelength(Angstrom) Flux(erg/s/cm^2/Angstrom)",
    fmt="%.6e"
)

# =========================================================
# 12. SAVE SENSITIVITY (THIS IS WHAT YOU USE FOR SN)
# =========================================================
np.savetxt(
    "sensitivity.txt",
    np.column_stack((star_wavelengths, sensitivity)),
    header="Wavelength(Angstrom) Sensitivity",
    fmt="%.6e"
)

print("Saved: calibrated_hiltner600.txt")
print("Saved: sensitivity.txt (USE THIS FOR SUPERNOVA)")

import numpy as np
import plotly.graph_objects as go
# from scipy.ndimage import gaussian_filter1d  # removed

# =========================================================
# 1. LOAD IMPROVED SENSITIVITY FUNCTION
# =========================================================
wave_sens, sensitivity = np.loadtxt(
    "sensitivity.txt",
    unpack=True
)

# =========================================================
# 2. SN exposure time
# =========================================================
sn_exptime = hdr['EXPTIME']  # from SN FITS header

# =========================================================
# 3. Convert SN (ADU → counts/sec)
# =========================================================
sn_rate = spectrum_smoothed / sn_exptime

# =========================================================
# 4. Interpolate sensitivity onto SN wavelength grid
# =========================================================
sens_interp = np.interp(
    wavelengths,
    wave_sens,
    sensitivity,
    left=np.nan,
    right=np.nan
)

# =========================================================
# 5. Apply calibration
# =========================================================
mask = (
    np.isfinite(sens_interp) &
    np.isfinite(sn_rate) &
    (sn_rate > 0)
)

sn_flux_calibrated = np.full_like(sn_rate, np.nan, dtype=float)
sn_flux_calibrated[mask] = sn_rate[mask] * sens_interp[mask]

# =========================================================
# 6. Fill gaps (NO SMOOTHING)
# =========================================================
valid = np.isfinite(sn_flux_calibrated)

sn_flux_filled = np.interp(
    wavelengths,
    wavelengths[valid],
    sn_flux_calibrated[valid]
)

# =========================================================
# 7. PLOT CALIBRATED SN SPECTRUM (UNSMOOTHED)
# =========================================================
fig = go.Figure()

fig.add_trace(go.Scatter(
    x=wavelengths,
    y=sn_flux_filled,
    mode='lines',
    name='Flux-Calibrated SN Spectrum (Unsmoothed)',
    line=dict(color='darkred')
))

# ---------------------------------------------------------
# Set wavelength range
# ---------------------------------------------------------
#fig.update_xaxes(range=[4500, 7000])

# ---------------------------------------------------------
# H-alpha reference lines
# ---------------------------------------------------------
fig.add_vline(
    x=6563,
    line_width=2,
    line_dash="dash",
    line_color="blue"
)

fig.add_vline(
    x=6739,
    line_width=2,
    line_dash="dash",
    line_color="green"
)

# ---------------------------------------------------------
# Annotations (labels on x-axis)
# ---------------------------------------------------------
fig.add_annotation(
    x=6563,
    y=0,
    xref="x",
    yref="paper",
    text="H-α Rest Wavelength, 6565 Å",
    showarrow=False,
    yanchor="top",
    textangle=0
)

fig.add_annotation(
    x=6739,
    y=0,
    xref="x",
    yref="paper",
    text="H-α Observed Wavelength, 6739 Å",
    showarrow=False,
    yanchor="top",
    textangle=0
)

# ---------------------------------------------------------
# Layout
# ---------------------------------------------------------
fig.update_layout(
    title='Flux-Calibrated Supernova Spectrum for 2026atw',
    xaxis_title='Wavelength (Å)',
    yaxis_title='Flux (erg s⁻¹ cm⁻² Å⁻¹)',
    template='plotly_white'
)

fig.show()

# =========================================================
# 8. SAVE FINAL CALIBRATED SN SPECTRUM
# =========================================================
np.savetxt(
    "calibrated_supernova_2026atw.txt",
    np.column_stack((wavelengths, sn_flux_filled)),
    header="Wavelength(Angstrom) Flux(erg/s/cm^2/Angstrom)",
    fmt="%.6e"
)

print("Saved: calibrated_supernova_2026atw.txt")

import numpy as np
import plotly.graph_objects as go
# from scipy.ndimage import gaussian_filter1d  # removed

# =========================================================
# 1. LOAD IMPROVED SENSITIVITY FUNCTION
# =========================================================
wave_sens, sensitivity = np.loadtxt(
    "sensitivity.txt",
    unpack=True
)

# =========================================================
# 2. SN exposure time
# =========================================================
sn_exptime = hdr['EXPTIME']  # from SN FITS header

# =========================================================
# 3. Convert SN (ADU → counts/sec)
# =========================================================
sn_rate = spectrum_smoothed / sn_exptime

# =========================================================
# 4. Interpolate sensitivity onto SN wavelength grid
# =========================================================
sens_interp = np.interp(
    wavelengths,
    wave_sens,
    sensitivity,
    left=np.nan,
    right=np.nan
)

# =========================================================
# 5. Apply calibration
# =========================================================
mask = (
    np.isfinite(sens_interp) &
    np.isfinite(sn_rate) &
    (sn_rate > 0)
)

sn_flux_calibrated = np.full_like(sn_rate, np.nan, dtype=float)
sn_flux_calibrated[mask] = sn_rate[mask] * sens_interp[mask]

# =========================================================
# 6. Fill gaps (NO SMOOTHING)
# =========================================================
valid = np.isfinite(sn_flux_calibrated)

sn_flux_filled = np.interp(
    wavelengths,
    wavelengths[valid],
    sn_flux_calibrated[valid]
)

# =========================================================
# 7. PLOT CALIBRATED SN SPECTRUM (STATIC, CLEAN)
# =========================================================
fig = go.Figure()

# SN spectrum (black line)
fig.add_trace(go.Scatter(
    x=wavelengths,
    y=sn_flux_filled,
    mode='lines',
    name='Flux-Calibrated SN Spectrum',
    line=dict(color='black')
))

# Set wavelength range
fig.update_xaxes(range=[4500, 7000])

# ---------------------------------------------------------
# H-α lines
# ---------------------------------------------------------
fig.add_trace(go.Scatter(
    x=[6563, 6563],
    y=[np.nanmin(sn_flux_filled), np.nanmax(sn_flux_filled)],
    mode='lines',
    name='H-𝛼, Rest Wavelength, 6565 Å',
    line=dict(color='blue', dash='dash')
))

fig.add_trace(go.Scatter(
    x=[6739, 6739],
    y=[np.nanmin(sn_flux_filled), np.nanmax(sn_flux_filled)],
    mode='lines',
    name='H-𝛼, Observed Wavelength, 6739 Å',
    line=dict(color='cyan', dash='dash')
))

# Shaded H-α region
fig.add_vrect(
    x0=6563, x1=6739,
    fillcolor="rgba(0, 0, 255, 0.08)",
    layer="below",
    line_width=0
)

fig.add_annotation(
    x=(6563 + 6739) / 2,
    y=0.95,
    xref="x",
    yref="paper",
    text="H-𝛼",
    showarrow=False,
    font=dict(size=14)
)

# ---------------------------------------------------------
# H-β lines
# ---------------------------------------------------------
fig.add_trace(go.Scatter(
    x=[4861, 4861],
    y=[np.nanmin(sn_flux_filled), np.nanmax(sn_flux_filled)],
    mode='lines',
    name='H-β Rest Wavelength, 4861 Å',
    line=dict(color='red', dash='dash')
))

fig.add_trace(go.Scatter(
    x=[4992, 4992],
    y=[np.nanmin(sn_flux_filled), np.nanmax(sn_flux_filled)],
    mode='lines',
    name='H-β Observed Wavelength, 4992 Å',
    line=dict(color='pink', dash='dash')
))

# Shaded H-β region
fig.add_vrect(
    x0=4861, x1=4992,
    fillcolor="rgba(255, 0, 0, 0.08)",
    layer="below",
    line_width=0
)

fig.add_annotation(
    x=(4861 + 4992) / 2,
    y=0.95,
    xref="x",
    yref="paper",
    text="H-β",
    showarrow=False,
    font=dict(size=14)
)

# ---------------------------------------------------------
# Layout (static figure)
# ---------------------------------------------------------
fig.update_layout(
    title='Flux-Calibrated Supernova Spectrum for 2026atw',
    xaxis_title='Wavelength (Å)',
    yaxis_title='Flux (erg s⁻¹ cm⁻² Å⁻¹)',
    template='plotly_white',
    showlegend=True
)

fig.update_yaxes(range=[0, 200])

fig.show(config={"staticPlot": True})

# =========================================================
# 8. SAVE FINAL CALIBRATED SN SPECTRUM
# =========================================================
np.savetxt(
    "calibrated_supernova_2026atw.txt",
    np.column_stack((wavelengths, sn_flux_filled)),
    header="Wavelength(Angstrom) Flux(erg/s/cm^2/Angstrom)",
    fmt="%.6e"
)

print("Saved: calibrated_supernova_2026atw.txt")

import numpy as np
import plotly.graph_objects as go

# =========================================================
# 1. Plot flux-calibrated Hiltner 600 spectrum (STATIC)
# =========================================================
fig = go.Figure()

fig.add_trace(go.Scatter(
    x=star_wavelengths,
    y=flux_calibrated,
    mode="lines",
    name="Flux-Calibrated Hiltner 600",
    line=dict(color="black")
))

fig.add_trace(go.Scatter(
    x=star_wavelengths,
    y=interp_std_flux,
    mode="lines",
    name="Reference Flux from fhilt600.dat.txt",
    line=dict(color="blue", dash="dot")
))

fig.update_layout(
    title="Flux-Calibrated Hiltner 600 Spectrum",
    xaxis_title="Wavelength (Å)",
    yaxis_title="Flux (erg s⁻¹ cm⁻² Å⁻¹)",
    template="plotly_white",
    showlegend=True
)

# Make x-axis slightly cleaner if you want (optional)
fig.update_xaxes(range=[np.nanmin(star_wavelengths), np.nanmax(star_wavelengths)])

# =========================================================
# 2. Render as STATIC (non-interactive)
# =========================================================
fig.show(config={"staticPlot": True})

